#define CHORDAL_HOLD
#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "zepxG/ZPDwxz"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define LANG_CHANGE_DEFAULT LANG_CHANGE_CTRL_SHIFT
