#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "zepxG/DzNApM"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#undef RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_STARTUP_SPD 60

#define UNICODE_ENABLE
#define UNICODE_SELECTED_MODES UC_WINC
